#!/bin/bash

set -e

/usr/bin/docker rm --force s3proxy &>/dev/null || true
/usr/bin/docker pull andrewgaul/s3proxy
/usr/bin/docker run --publish 80:80 --env S3PROXY_AUTHORIZATION=none --detach --name s3proxy andrewgaul/s3proxy

